### ISSUE TITLE
Printing arival time and departure time with zero value

### ISSUE THREAD

**Issue by Zarthan66** [Zarthan66/Bus-Reservation#4]
The issue happen when printing the arrival time and departure time that has zero value.

It will print like 0:0, 20:0, 0:25 instead of 00:00, 20:00, 00:25.

**Comment by FlamingHub** [comment]
Okay , on it

**Comment by FlamingHub** [comment]
When one enters 0000 as a int value the int automatically becomes 0 , the solution is using strings
